meta_product_name: "Find Your Buddy"
meta_title: "FYB-gaming - The pleasure of gaming with people who play like you"
meta_description: "With FYB select and match your best buddy"
meta_image: "fyb-og.jpg"            # should exist in `app/assets/images/`
twitter_account: "@lewagonnantes"   # required for Twitter Cards
